mongodb:
  # https://artifacthub.io/packages/helm/bitnami/mongodb?modal=values
  nameOverride: "ps2alerts-db"

  image:
    tag: 5.0.8-debian-10-r17

  auth:
    rootUser: "foobar"
    rootPassword: "foobar123"

  resources:
    limits:
      memory: "2Gi"
    requests:
      cpu: "300m"
      memory: "2Gi"

  persistence:
    size: 1Gi

  # This is required to ensure the pods are terminated FIRST before a new one is made otherwise we'll have a PVC lock. This will result in ~30s downtime *but* it will work.
  updateStrategy:
    type: Recreate
  # Pod has 30 seconds to terminate before they get force terminated
  terminationGracePeriodSeconds: 30
