apiVersion: v1
kind: Service
metadata:
  name: ps2alerts-aggregator
  namespace: ps2alerts-tests
  labels:
    app: ps2alerts-aggregator
spec:
  type: ClusterIP
  selector:
    app: ps2alerts-aggregator
  ports:
    - name: app
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps2alerts-aggregator
  namespace: ps2alerts-tests
  labels:
    app: ps2alerts-aggregator
spec:
  replicas: 1 # And there will always only be 1
  selector:
    matchLabels:
      app: ps2alerts-aggregator
  template:
    metadata:
      labels:
        app: ps2alerts-aggregator
    spec:
      containers:
        - name: application
          image: maelstromeous/ps2alerts:ps2alerts-aggregator-production-latest
          imagePullPolicy: Always
          startupProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - cat /app/ready.file | grep -i "ready"
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 6 # 30s
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - cat /app/ready.file | grep -i "ready"
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3 # 30s
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - ps -ef | grep "run start" | grep -v grep
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
          env:
            - name: NODE_ENV
              value: "production"
            - name: VERSION
              value: "testing"
            - name: CENSUS_SERVICE_ID
              value: "ps2alertsdotcom"
            - name: CENSUS_ENVIRONMENT
              value: "ps2"
            - name: CENSUS_EVENTS
              value: "Death"
            - name: RABBITMQ_HOST
              value: "ps2alerts-rabbitmq"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASS
              value: "guest"
            - name: RABBITMQ_API_QUEUE
              value: "api-queue-tests"
            - name: RABBITMQ_API_QUEUE_DELAY
              value: "api-queue-delay-tests"
            - name: REDIS_HOST
              value: "ps2alerts-redis"
            - name: REDIS_DB
              value: "0"
            - name: LOGGER_TRANSPORTS
              value: "console"
            - name: INTERNAL_API_HOST
              value: "http://ps2alerts-api:3000"
            - name: INTERNAL_API_USER
              value: "ps2alerts"
            - name: INTERNAL_API_PASS
              value: "foobar"
