apiVersion: v1
kind: Service
metadata:
  name: ps2alerts-rabbitmq
  namespace: ps2alerts-tests
  labels:
    app: ps2alerts-rabbitmq
spec:
  type: ClusterIP
  selector:
    app: ps2alerts-rabbitmq
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ps2alerts-rabbitmq
  namespace: ps2alerts-tests
spec:
  selector:
    matchLabels:
      app: ps2alerts-rabbitmq
  serviceName: ps2alerts-rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: ps2alerts-rabbitmq
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: rabbitmq
          image: rabbitmq:3.8-management
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672
            - name: amqp
              protocol: TCP
              containerPort: 5672
          readinessProbe:           # This readiness probe will delay the startup of the nex pod for 30 seconds. It ensures
            exec:                   # the node is most probably in a state that let the next node connect to this one.
              command: ["true"]     # Doing a real liveness or readiness probe will result in a stuck statfult set if the
            initialDelaySeconds: 30 # cluster is in a "pause_minority" state. In this state all health checks provided
            timeoutSeconds: 5       # by rabbitmq will fail, but the node should _not_ be restarted.
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RABBITMQ_NODENAME
              value: "rabbit@$(MY_POD_NAME).ps2alerts-rabbitmq.ps2alerts-tests.svc.cluster.local"
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
            - name: RABBITMQ_VM_MEMORY_HIGH_WATERMARK
              value: "0.49"
            - name: RABBITMQ_ERLANG_COOKIE
              value: erlang-cookie-placeholder
            - name: RABBITMQ_DEFAULT_USER
              value: guest
            - name: RABBITMQ_DEFAULT_PASS
              value: guest
            - name: CLEANUP_WARN_ONLY
              value: "false"
